const constants = {

    CREATE_USER_PENDING: "CREATE_USER_PENDING",

    CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",

    CREATE_USER_FAILED: " CREATE_USER_FAILED",

    GET_USER_PENDING: "GET_USER_PENDING",

    GET_USER_SUCCESS: "GET_USER_SUCCESS",

    GET_USER_FAILED: "GET_USER_FAILED",

    GET_USERS_PENDING: "GET_USERS_PENDING",

    GET_USERS_SUCCESS: "GET_USERS_SUCCESS",

    GET_USERS_FAILED: "GET_USERS_FAILED",

    UPDATE_USER_PENDING: "UPDATE_USER_PENDING",

    UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",

    UPDATE_USER_FAILED: "UPDATE_USER_FAILED",

    DELETE_USER_PENDING: "DELETE_USER_PENDING",

    DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",

    DELETE_USER_FAILED: "DELETE_USER_FAILED",

}


export default constants